@file:Suppress("UNUSED")
package mcDevNight.example

import mcDevNight.example.common.CommonProxy
import net.minecraftforge.common.config.Configuration
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.Mod.*
import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.SidedProxy
import net.minecraftforge.fml.common.event.FMLInitializationEvent
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent
import java.io.File

/**
 * @author C6H2Cl2
 */

@Mod(modid = MOD_ID, name = MOD_NAME, version = VERSION, dependencies = DEPENDENCIES, useMetadata = true, acceptedMinecraftVersions = "1.10.2")
class ExampleModCore {

    companion object {
        @JvmStatic
        @Metadata
        lateinit var META: ModMetadata

        @JvmStatic
        @SidedProxy(serverSide = "mcDevNight.example.common.CommonProxy", clientSide = "mcDevNight.example.client.ClientProxy")
        lateinit var PROXY: CommonProxy

        @JvmStatic
        @Instance
        lateinit var INSTANCE: ExampleModCore
    }

    @EventHandler
    fun preinit(event: FMLPreInitializationEvent) {
        loadMeta()
        getConfig()
        register()
        Registry.preinit(event)
        if(event.side.isClient) {
            texture()
        }
    }

    @EventHandler
    fun init(event: FMLInitializationEvent) {
        recipe()
        Registry.init(event)
    }

    @EventHandler
    fun postinit(event: FMLPostInitializationEvent) {

    }

    private fun loadMeta() {
        META.modId = MOD_ID
        META.name = MOD_NAME
        META.version = VERSION
        META.authorList.add("YourName")
        META.url = "http://minecraft.curseforge.com/projects/$MOD_ID"
        META.autogenerated = false
    }

    private fun getConfig() {
        val cfg = Configuration(File(PROXY.getDir(), "config/$MOD_NAME.cfg"))
        cfg.load()
        //Configの読み込み
        cfg.save()
    }
}